export const ALL_BOOKS_REQUESTED = 'ALL_BOOKS_REQUESTED';
export const ALL_BOOKS_SUCCESS = 'ALL_BOOKS_SUCCESS';
export const ALL_BOOKS_FAILURE = 'ALL_BOOKS_FAILURE';
export const SET_FILTER_REQUESTED = 'SET_FILTER_REQUESTED';
